name: deploy bevel protractor to the github pages 

on:
 push:
  branches:
    - main
 workflow_dispatch:


jobs:
  build-and-deploy:
    if: contains(github.event.head_commit.message,'build')

    runs-on: ubuntu-latest

    steps:

    - name: checkuot rpeository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: create .nojekyll file
      run: touch .nojekyll


    - name: Deploy to github pages 
      uses: peaceiris/actions-gh-pages@v4
      with:

        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./

        publish_branch: gh-pages
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'



 